[package]
name = "damnhttp-git"
description = "The `GitEngine` trait and its implementations for Damn HTTP: local operations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
damnhttp-core = { workspace = true }

[lints]
workspace = true
