[package]
name = "damnhttp-core"
description = "Models, file format, variable resolution and detection rules for Damn HTTP"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
